### ISSUE TITLE
Animations in Jupyter Notebook / Lab (with IRKernel) not working

### ISSUE THREAD

**Issue by jeanmonet** [ggobi/tourr#117]
Hi,

I have been trying to make animations work in Jupyter Notebook (using IRKernel) with no success. I believe the rendering loop just exists after the first iteration (tryCatch block?).

Below is a screenshot of the output:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/15112920/221529839-918ffef5-b850-4266-acf4-48ffc1ec2468.png">

Is there any way to make animations work in Jupyter (with IRKernel), or at least export animations to other formats?

When trying to use the `animate` library, for instance to `saveGIF` (inside the Jupyter Notebook), I get the same result: only the first frame is saved.

**Comment by dicook** [comment]
Hi @jeanmonet I've just added a function that will generate an animation using plotly. This uses the save_history function. In general, this might be an easier way to work, because it will generate a sequence of frames that can be used to make animations in other systems. Otherwise, take a look at the detourr package, https://github.com/casperhart/detourr which has a tight connection between the animate function and viewing with javascript.

**Comment by jeanmonet** [comment]
Hi, thank you for the addition!
